#!/bin/bash
# =====================================================================
# Title: Sienna Config Watcher - Configuration File
# Author: Jannik Altgen
# Date: January 1, 2024
# Purpose:  Configuration variables for the Sienna config watcher. 
# Usage: Set vars below. They will be sourced into the main script.
# Dependencies: n/a
# =====================================================================

########################################
#MODIFY THE FOLLOWING TO SUIT YOUR SETUP

# user and group names of the user that runs the Sienna NDIPE. Most likely "ubuntu" and "ubuntu".
SIENNA_USER="ubuntu"
SIENNA_GROUP="ubuntu"

#postfix for last conf file generated by sienna / most likely won't change
LAST_BACKUP_POSTFIX='-LASTFLUSH'
#postfix for backup conf file auto-generated from sienna / most likely won't change
PRE_BACKUP_POSTFIX='-PRELAUNCH'

# absolute path to the "golden" backup config file, that will be used if the running conf above is broken.
FULL_BACKUP_PATH="/home/ubuntu/config-saver/backups/RouterConfig.xml.bak"

#running conf name (from GUI or NDIPE/resources/configurations/)
RUNNING_CONF_NAME="RouterConfig.xml"
RUNNING_CONF_PATH='/home/ubuntu/NDIPE/resources/configurations'

#################################
# DO NOT MODIFY BEYOND THIS POINT
# path concatenations for easier use in script 
FULL_CONF_PATH="$RUNNING_CONF_PATH/$RUNNING_CONF_NAME"
PRE_BACKUP_PATH="$RUNNING_CONF_PATH/$RUNNING_CONF_NAME$PRE_BACKUP_POSTFIX"
LAST_BACKUP_PATH="$RUNNING_CONF_PATH/$RUNNING_CONF_NAME$LAST_BACKUP_POSTFIX"

